version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: demo-app-{{ checksum "package-lock.json" }}
      - run:
          name: "install"
          command: npm install
      - save_cache:
          key: demo-app-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: "test cover"
          command: npm run test:coverage
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: "deploy to heroku"
          command: git push https://heroku:17f11717-c5a0-4035-8d60-fb20422c7eb6@git.heroku.com/desolate-ocean-50585.git master
workflows:
  build-and-test:
    jobs:
      - test
      - deploy:
          requires:
            - test

